/*
-- Query: select * from es_dev.es_product
LIMIT 0, 1000

-- Date: 2013-09-26 20:59
*/
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (80,10,'Jeans','ADVJN001','Stretchable Jeans','Stretchable Jeans',900,1050,60,5,NULL,'jeans.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (81,10,'Jeans','ADVJN002','Comfort fit','Comfort fit',1000,1100,50,0,NULL,'jeans2.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (82,10,'Jeans','ADVJN003','Straight Fit','Straight Fit',850,1100,90,7,NULL,'jeans3.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (83,10,'Shirt','ADVSH001','Casual wear','Casual wear',1200,1400,30,0,NULL,'shirt1.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (84,10,'Shirt','ADVSH002','Casual wear','Casual wear',1000,1200,80,5,NULL,'shirt2.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (85,10,'Shirt','ADVSH003','Casual wear','Casual wear',800,1050,40,10,NULL,'shirt3.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (86,10,'tShirt','ADVTS001','Round neck','Round neck',400,500,90,5,NULL,'tshirt1.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (87,10,'tShirt','ADVTS002','Round neck','Round neck',300,400,110,10,NULL,'tshirt2.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (88,10,'tShirt','ADVTS003','Colarred Tshirt','Colarred Tshirt',400,650,45,9,NULL,'tshirt3.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (89,11,'Nipple','MOTNP001','Nipple 2A','Nipple 2A',300,320,50,0,NULL,'nipples1.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (90,11,'Nipple','MOTNP002','Nipple 3A','Nipple 3A',400,460,70,0,NULL,'nipples2.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (91,12,'Nipple','PIGNP001','Nipple 1S','Nipple 1S',150,180,21,0,NULL,'nipples3.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (92,12,'Wipes','PIGWP001','Wipes wet','Wipes wet',500,600,70,5,NULL,'wipes3.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (93,12,'Wipes','PIGWP002','Wipes dry','Wipes dry',300,320,67,0,NULL,'wipes2.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (94,11,'Wipes','MOTWP001','Wipes wet','Wipes wet',200,300,22,10,NULL,'wipes1.png','Active',NULL,NULL);
INSERT INTO `es_product` (`prodid`,`brandid`,`category`,`prodcode`,`name`,`description`,`price`,`displayprice`,`quantity`,`discount`,`instock`,`imgurl`,`status`,`latupddttm`,`lastupduser`) VALUES (95,11,'Wipes','MOTWP002','Wipes Dry','Dry wipes for better comfort',200,300,22,10,NULL,'wipes4.png','Active',NULL,NULL);
